/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.75
 * Generated at: 2023-06-16 08:56:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class update_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/top.jsp", Long.valueOf(1686846378000L));
    _jspx_dependants.put("/user.jsp", Long.valueOf(1686846529000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<link href=\"style.css?after\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>수강신청 사용자 정보 수정</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<link href=\"style.css?after\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("</head>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("<br>\n");
      out.write("<br>\n");
      out.write("<table class=\"top\" width=\"500px\" align=\"right\">\n");
      out.write("	<tr>\n");
      out.write("		<td>\n");
      out.write("			");
 String session_id = (String) session.getAttribute("user");
		if (session_id == null) {
      out.write("\n");
      out.write("			<p>로그인을 해주세요.</p> ");
} else {
      out.write("\n");
      out.write("			<p>");
      out.print(session_id);
      out.write("님 방문을 환영합니다.\n");
      out.write("			</p>\n");
      out.write("		</td>\n");
      out.write("		<td>\n");
      out.write("			");
 if (session_id.length() == 7) {
      out.write(" <a href=\"update.jsp\">마이페이지</a> ");
} else if (session_id.length() == 5) {
      out.write("\n");
      out.write("			<a href=\"update_prof.jsp\">마이페이지</a> ");
 }
				else { 
      out.write("\n");
      out.write("				<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p> ");
} 
      out.write(' ');
}
      out.write("\n");
      out.write("		</td>\n");
      out.write("		<td>\n");
      out.write("			");
 String log;
			if (session_id == null)
			log = "<a href=login.jsp>로그인</a>";
			else log = "<a href=logout.jsp>로그아웃</a>"; 
      out.write("\n");
      out.write("			<p class=\"title\">");
      out.print(log);
      out.write("</p>\n");
      out.write("		</td>\n");
      out.write("\n");
      out.write("		<td></td>\n");
      out.write("	</tr>\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("\n");
      out.write('\n');
      out.write('	');
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<link href=\"style.css?after\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("</head>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("<br>\n");
      out.write("<br>\n");
      out.write("<div class=\"topButton\">\n");
      out.write("	<table class=\"top\" width=\"75%\" align=\"center\">\n");
      out.write("		<tr>\n");
      out.write("			<td><a href=\"all_course.jsp\">전체과목 조회</a></td>\n");
      out.write("			<td><a href=\"insert.jsp\">수강신청 입력</a></td>\n");
      out.write("			<td><a href=\"delete.jsp\">수강신청 조회</a></td>\n");
      out.write("			<td><a href=\"cart.jsp\">장바구니</a></td>\n");
      out.write("			<td><a href=\"history.jsp\">개별수강 이력</a></td>\n");
      out.write("		</tr>\n");
      out.write("	</table>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("	<br>\n");
      out.write("	<center>\n");
      out.write("		<div id=\"updateMessage\"></div>\n");
      out.write("	</center>\n");
      out.write("	<br>\n");
      out.write("	<br>\n");
      out.write("	<br>\n");
      out.write("	<table width=\"70%\" align=\"center\" class=\"mypage-table\" border>\n");
      out.write("		<form method=\"post\" action=\"update_verify.jsp\">\n");
      out.write("			<tr height='50px'>\n");
      out.write("				<td><div>\n");
      out.write("						<b>학번</b>\n");
      out.write("					</div></td>\n");
      out.write("				<td><div name=\"userID\">");
      out.print(session_id);
      out.write("</div></td>\n");
      out.write("			</tr>\n");
      out.write("			<tr height='50px'>\n");
      out.write("				<td><div>\n");
      out.write("						<b>패스워드</b>\n");
      out.write("					</div></td>\n");
      out.write("				<td><div>\n");
      out.write("						<input type=\"text\" name=\"userPassword\" class=\"editable\">\n");
      out.write("					</div></td>\n");
      out.write("			</tr>\n");
      out.write("			<tr height='50px'>\n");
      out.write("				<td><div>\n");
      out.write("						<b>이름</b>\n");
      out.write("					</div></td>\n");
      out.write("				<td><div name=\"userName\"></div></td>\n");
      out.write("			</tr>\n");
      out.write("			<tr height='50px'>\n");
      out.write("				<td><div>\n");
      out.write("						<b>전공</b>\n");
      out.write("					</div></td>\n");
      out.write("				<td><div name=\"userMajor\"></div></td>\n");
      out.write("			</tr>\n");
      out.write("			<tr height='50px'>\n");
      out.write("				<td><div>\n");
      out.write("						<b>학년</b>\n");
      out.write("					</div></td>\n");
      out.write("				<td><div name=\"userGrade\"></div></td>\n");
      out.write("			</tr>\n");
      out.write("\n");
      out.write("			<tr height='50px'>\n");
      out.write("				<td><div>\n");
      out.write("						<b>이메일</b>\n");
      out.write("					</div></td>\n");
      out.write("				<td><div>\n");
      out.write("						<input type=\"text\" name=\"userEmail\" class=\"editable\">\n");
      out.write("					</div></td>\n");
      out.write("			</tr>\n");
      out.write("			<tr height='50px'>\n");
      out.write("				<td><div>\n");
      out.write("						<b>주소</b>\n");
      out.write("					</div></td>\n");
      out.write("				<td><div>\n");
      out.write("						<input type=\"text\" name=\"userAddress\" class=\"editable\">\n");
      out.write("					</div></td>\n");
      out.write("			</tr>\n");
      out.write("\n");
      out.write("			<tr height='50px'>\n");
      out.write("				<td><div>\n");
      out.write("						<b>전화번호</b>\n");
      out.write("					</div></td>\n");
      out.write("				<td><div>\n");
      out.write("						<input type=\"text\" name=\"userPhone\" class=\"editable\">\n");
      out.write("					</div></td>\n");
      out.write("			</tr>\n");
      out.write("			<tr height='20px'>\n");
      out.write("				<td colspan=2><div align=\"center\">\n");
      out.write("						<input type=\"SUBMIT\" name=\"Submit\" value=\"수정\">\n");
      out.write("					</div></td>\n");
      out.write("			</tr>\n");
      out.write("		</form>\n");
      out.write("		");

		if (session_id == null)
			response.sendRedirect("login.jsp");
		else {
			String driver = "oracle.jdbc.driver.OracleDriver";
			String url = "jdbc:oracle:thin:@localhost:1521:xe";
			String user = "leebk";
			String password = "1124";
			Connection myConn = null;
			Statement stmt = null;
			try {
				Class.forName(driver);
				myConn = DriverManager.getConnection(url, user, password);
				myConn.setAutoCommit(false);
				stmt = myConn.createStatement();
			} catch (ClassNotFoundException e) {
				System.out.println("jdbc driver 로딩 실패");
			} catch (SQLException e) {
				System.out.println("오라클 연결 실패");
			}
			String mySQL = "select s_pwd, s_name, s_major, s_grade, s_email, s_phone, s_address from student where s_id=" + session_id + "";
			ResultSet rs = stmt.executeQuery(mySQL);
			if (rs.next()) {
				String pwd = rs.getString("s_pwd");
				String name = rs.getString("s_name");
				String major = rs.getString("s_major");
				Integer grade = rs.getInt("s_grade");
				String email = rs.getString("s_email");
				String phone = rs.getString("s_phone");
				String addr = rs.getString("s_address");
				
		
      out.write("\n");
      out.write("		<script>\n");
      out.write("		      document.getElementsByName(\"userPassword\")[0].value = '");
      out.print(pwd);
      out.write("';\n");
      out.write("		      document.getElementsByName(\"userName\")[0].innerHTML = \"");
      out.print(name);
      out.write("\";\n");
      out.write("		      document.getElementsByName(\"userMajor\")[0].innerHTML = \"");
      out.print(major);
      out.write("\";\n");
      out.write("		      document.getElementsByName(\"userGrade\")[0].innerHTML = '");
      out.print(grade);
      out.write("';\n");
      out.write("		      document.getElementsByName(\"userEmail\")[0].value = '");
      out.print(email);
      out.write("';\n");
      out.write("		      document.getElementsByName(\"userPhone\")[0].value = '");
      out.print(phone);
      out.write("';\n");
      out.write("		      document.getElementsByName(\"userAddress\")[0].value = '");
      out.print(addr);
      out.write("';\n");
      out.write("		</script>\n");
      out.write("		");
}
   else{
   }
}
      out.write("\n");
      out.write("	</table>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
